### ISSUE TITLE
Провести проверку на большом файле

### ISSUE THREAD

**Issue by alexkoss** [Kotanka/Grouping-strings#1]
Добрый день! Меня зовут Александр, сотрудник компании БалтИнфоКом.

Предлагаю осуществить проверку на большом файле.

Файл: https://github.com/PeacockTeam/new-job/releases/download/v1.0/lng-big.7z

В ответе должно быть количество групп и время выполнения.

**Comment by Kotanka** [comment]
Добрый день!

Сейчас моя программа выдает ошибку по памяти при попытке обработать файл lng-big. Мне переписать алгоритм, чтобы он укладывался по памяти? 
И учитывать ли в замере времени то время, которое требуется на записывание итоговых групп в файл?

**Comment by alexkoss** [comment]
Да, переписать. Да, учитывать.

**Comment by Kotanka** [comment]
Добрый день!
Переписала алгоритм, актуальная версия в гите. Количество групп после группировки строк из файла lng-big.csv - 105036, время выполнения программы - 29,3 секунды.
